/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p AccountsUserInterface com.unikylin.Kiran.SystemDaemon.Accounts.User.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */
#include "accounts-user-interface.h"
#include "accounts-interface.h"

/*
 * Implementation of interface class ComUnikylinKiranSystemDaemonAccountsUserInterface
 */

UserInterface::UserInterface(const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface("com.kylinsec.Kiran.SystemDaemon.Accounts", path, staticInterfaceName(), connection,
                             parent)
{
    QDBusConnection::systemBus().connect(AccountsInterface::staticInterfaceName(),
                                         path,
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged", this,
                                         SLOT(handlePropertiesChanged(QDBusMessage)));
}

UserInterface::~UserInterface()
{
    QDBusConnection::systemBus().disconnect(AccountsInterface::staticInterfaceName(),
                                            path(),
                                            "org.freedesktop.DBus.Properties",
                                            "PropertiesChanged", this,
                                            SLOT(handlePropertiesChanged(QDBusMessage)));
}

void UserInterface::handlePropertiesChanged(QDBusMessage msg)
{
    QList<QVariant> arguments = msg.arguments();
    if (arguments.size() < 1)
    {
        return;
    }
    QVariantMap changeProperties = qdbus_cast<QVariantMap>(arguments.at(1).value<QDBusArgument>());
    for (auto iter = changeProperties.begin();
         iter != changeProperties.end();
         iter++)
    {
        emit propertyChanged(path(), iter.key(), iter.value());
    }
}
