/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.kylinsec.Kiran.SystemDaemon.Greeter.xml -p GreeterInterface
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "greeter-dbus-interface.h"

/*
 * Implementation of interface class GreeterDBusInterface
 */

GreeterDBusInterface::GreeterDBusInterface(const QString &service,
                                                                                           const QString &path,
                                                                                           const QDBusConnection &connection,
                                                                                           QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

GreeterDBusInterface::~GreeterDBusInterface()
{
}

