/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p GreeterSettingsDBusProxy com.kylinsec.Kiran.SessionDaemon.GreeterSettings.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "greeter-settings-dbus-proxy.h"

/*
 * Implementation of interface class ComKylinsecKiranSystemDaemonGreeterSettingsInterface
 */

ComKylinsecKiranSystemDaemonGreeterSettingsInterface::ComKylinsecKiranSystemDaemonGreeterSettingsInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComKylinsecKiranSystemDaemonGreeterSettingsInterface::~ComKylinsecKiranSystemDaemonGreeterSettingsInterface()
{
}
